name: Format

on:
  push:
    branches: [ master ]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Format Java code
        uses: axel-op/googlejavaformat-action@v3
        with:
          distribution: 'https://github.com/google/google-java-format/releases/download/v1.15.0/google-java-format-1.15.0-all-deps.jar'
          args: "--skip-sorting-imports --replace"
